import { useState, useCallback, useEffect, useMemo } from 'react'
import { useKV } from '@github/spark/hooks'
import { Toaster } from '@/components/ui/sonner'
import { toast } from 'sonner'
import { Layout } from '@/components/Layout'
import { Dashboard } from '@/components/views/Dashboard'
import { Schedule } from '@/components/views/Schedule'
import { ScheduleTemplates } from '@/components/views/ScheduleTemplates'
import { Courses } from '@/components/views/Courses'
import { People } from '@/components/views/People'
import { Analytics } from '@/components/views/Analytics'
import { TrainerAvailability } from '@/components/views/TrainerAvailability'
import { BurnoutDashboard } from '@/components/views/BurnoutDashboard'
import { TrainerWellness } from '@/components/views/TrainerWellness'
import { CertificationDashboard } from '@/components/views/CertificationDashboard'
import { Notifications } from '@/components/views/Notifications'
import { UserGuide } from '@/components/views/UserGuide'
import { NotificationPermissionBanner } from '@/components/NotificationPermissionBanner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  User,
  Session,
  Course,
  Enrollment,
  Notification,
  CertificationRecord,
  CheckInSchedule,
  RecoveryPlan,
  ScheduleTemplate,
  WellnessCheckIn
} from '@/lib/types'
import { useUtilizationNotifications } from '@/hooks/use-utilization-notifications'
import { useCertificationNotifications } from '@/hooks/use-certification-notifications'
import { usePushNotifications } from '@/hooks/use-push-notifications'
import { ensureAllTrainersHaveProfiles } from '@/lib/trainer-profile-generator'
import { createPreviewSeedData, PREVIEW_SEED_VERSION } from '@/lib/preview-seed-data'
import { getPreviewSeedMode, isPreviewSeedEnabled, PreviewSeedMode } from '@/lib/preview-mode'
import { RiskHistorySnapshot } from '@/lib/risk-history-tracker'

/**
 * Root application component for the TrainSync training management platform.
 *
 * Manages all persistent application state (users, sessions, courses,
 * enrollments, notifications, wellness records, and more) via KV-backed hooks,
 * and orchestrates navigation between the various views rendered inside the
 * shared {@link Layout}.
 *
 * Also handles automatic seeding of preview/demo data when the application is
 * launched in a preview environment, and wires up utilization and
 * certification notification hooks that generate in-app alerts.
 *
 * @returns The full application shell including the active view, a
 *   notification permission banner, and the toast container.
 */
function App() {
  const [activeView, setActiveView] = useState('dashboard')

  const previewSeedMode = getPreviewSeedMode()
  const previewSeedEnabled = isPreviewSeedEnabled(previewSeedMode)

  const [users, setUsers] = useKV<User[]>('users', [])
  const [sessions, setSessions] = useKV<Session[]>('sessions', [])
  const [courses, setCourses] = useKV<Course[]>('courses', [])
  const [enrollments, setEnrollments] = useKV<Enrollment[]>('enrollments', [])
  const [notifications, setNotifications] = useKV<Notification[]>('notifications', [])
  const [, setWellnessCheckIns] = useKV<WellnessCheckIn[]>('wellness-check-ins', [])
  const [, setRecoveryPlans] = useKV<RecoveryPlan[]>('recovery-plans', [])
  const [, setCheckInSchedules] = useKV<CheckInSchedule[]>('check-in-schedules', [])
  const [, setScheduleTemplates] = useKV<ScheduleTemplate[]>('schedule-templates', [])
  const [, setRiskHistorySnapshots] = useKV<RiskHistorySnapshot[]>('risk-history-snapshots', [])
  const [, setTargetTrainerCoverage] = useKV<number>('target-trainer-coverage', 4)
  const [previewSeedVersion, setPreviewSeedVersion] = useKV<string>('preview-seed-version', '')

  const { sendNotification } = usePushNotifications()

  /**
   * Populates all KV stores with deterministic preview seed data generated by
   * {@link createPreviewSeedData}, then records a versioned seed marker so the
   * seeding logic does not run again for the same mode.
   *
   * Passing `'off'` is a no-op. For all other modes (including `'manual'`),
   * the stored seed-version marker is always updated to reflect the applied mode.
   *
   * @param seedMode - The preview seed mode to apply. One of the
   *   {@link PreviewSeedMode} values or `'manual'`.
   */
  const applyPreviewSeedData = useCallback((seedMode: PreviewSeedMode | 'manual' = 'manual') => {
    if (seedMode === 'off') {
      return
    }

    const seedData = createPreviewSeedData()
    const seedMarker = `${PREVIEW_SEED_VERSION}:${seedMode}`

    setUsers(seedData.users)
    setSessions(seedData.sessions)
    setCourses(seedData.courses)
    setEnrollments(seedData.enrollments)
    setNotifications(seedData.notifications)
    setWellnessCheckIns(seedData.wellnessCheckIns)
    setRecoveryPlans(seedData.recoveryPlans)
    setCheckInSchedules(seedData.checkInSchedules)
    setScheduleTemplates(seedData.scheduleTemplates)
    setRiskHistorySnapshots(seedData.riskHistorySnapshots)
    setTargetTrainerCoverage(seedData.targetTrainerCoverage)
    setPreviewSeedVersion(seedMarker)

    toast.success('Preview test data loaded', {
      description: `Seeded ${seedData.users.length} users, ${seedData.sessions.length} sessions, and related edge-case data.`
    })
  }, [
    setUsers,
    setSessions,
    setCourses,
    setEnrollments,
    setNotifications,
    setWellnessCheckIns,
    setRecoveryPlans,
    setCheckInSchedules,
    setScheduleTemplates,
    setRiskHistorySnapshots,
    setTargetTrainerCoverage,
    setPreviewSeedVersion
  ])

  /**
   * Derived boolean that is `true` when at least one user, session, course, or
   * enrollment record already exists in the KV store. Used to warn the user
   * before overwriting data with seed data.
   */
  const hasExistingCoreData = useMemo(() => {
    return (users?.length || 0) > 0 ||
      (sessions?.length || 0) > 0 ||
      (courses?.length || 0) > 0 ||
      (enrollments?.length || 0) > 0
  }, [users?.length, sessions?.length, courses?.length, enrollments?.length])

  /**
   * Handles a user-initiated request to load preview seed data from the
   * Settings page. If core data already exists, shows a confirmation dialog
   * before overwriting it. Delegates to {@link applyPreviewSeedData}.
   */
  const handleLoadPreviewSeedData = useCallback(() => {
    if (hasExistingCoreData) {
      const shouldOverwrite = window.confirm(
        'This will overwrite existing local data in preview storage. Continue?'
      )

      if (!shouldOverwrite) {
        return
      }
    }

    applyPreviewSeedData('manual')
  }, [hasExistingCoreData, applyPreviewSeedData])

  /**
   * Handles a user-initiated request to wipe all preview data. Prompts the
   * user for confirmation, then clears every KV-backed collection (users,
   * sessions, courses, enrollments, notifications, wellness records, recovery
   * plans, check-in schedules, schedule templates, and risk history snapshots),
   * resets the target trainer coverage to its default, and removes any
   * `reminder-*` keys from `localStorage`.
   */
  const handleResetPreviewData = useCallback(() => {
    const confirmed = window.confirm(
      'Reset all local preview data (users, sessions, courses, notifications, wellness, templates, and history)? This cannot be undone.'
    )

    if (!confirmed) {
      return
    }

    setUsers([])
    setSessions([])
    setCourses([])
    setEnrollments([])
    setNotifications([])
    setWellnessCheckIns([])
    setRecoveryPlans([])
    setCheckInSchedules([])
    setScheduleTemplates([])
    setRiskHistorySnapshots([])
    setTargetTrainerCoverage(4)
    setPreviewSeedVersion('')

    if (typeof window !== 'undefined') {
      Object.keys(localStorage).forEach((key) => {
        if (key.startsWith('reminder-')) {
          localStorage.removeItem(key)
        }
      })
    }

    toast.success('Preview data reset complete', {
      description: 'All local preview records have been cleared.'
    })
  }, [
    setUsers,
    setSessions,
    setCourses,
    setEnrollments,
    setNotifications,
    setWellnessCheckIns,
    setRecoveryPlans,
    setCheckInSchedules,
    setScheduleTemplates,
    setRiskHistorySnapshots,
    setTargetTrainerCoverage,
    setPreviewSeedVersion
  ])

  useEffect(() => {
    if (!previewSeedEnabled) {
      return
    }

    const seedMarker = `${PREVIEW_SEED_VERSION}:${previewSeedMode}`
    const alreadySeededForMode = previewSeedVersion === seedMarker
    const hasExistingCoreData =
      (users?.length || 0) > 0 ||
      (sessions?.length || 0) > 0 ||
      (courses?.length || 0) > 0 ||
      (enrollments?.length || 0) > 0

    if (alreadySeededForMode) {
      return
    }

    if (previewSeedMode === 'full' && hasExistingCoreData) {
      return
    }

    applyPreviewSeedData(previewSeedMode)
  }, [
    previewSeedEnabled,
    previewSeedMode,
    previewSeedVersion,
    users,
    sessions,
    courses,
    enrollments,
    setUsers,
    setSessions,
    setCourses,
    setEnrollments,
    setNotifications,
    setWellnessCheckIns,
    setRecoveryPlans,
    setCheckInSchedules,
    setScheduleTemplates,
    setRiskHistorySnapshots,
    setTargetTrainerCoverage,
    setPreviewSeedVersion,
    applyPreviewSeedData
  ])

  useEffect(() => {
    if (users && users.length > 0) {
      const trainers = users.filter(u => u.role === 'trainer')
      const trainersWithoutProfiles = trainers.filter(t => !t.trainerProfile)

      if (trainersWithoutProfiles.length > 0) {
        const updatedUsers = ensureAllTrainersHaveProfiles(users)
        setUsers(updatedUsers)
      }
    }
  }, [])

  const safeUsers = users || []
  const safeSessions = sessions || []
  const safeCourses = courses || []
  const safeEnrollments = enrollments || []
  const safeNotifications = notifications || []

  /**
   * Creates a new {@link Notification} record with a generated ID and
   * timestamp, prepends it to the notifications KV store, fires a push
   * notification via {@link usePushNotifications}, and shows a toast for
   * high-priority or critical alerts.
   *
   * @param notification - All notification fields except the auto-generated
   *   `id` and `createdAt`.
   */
  const handleCreateNotification = useCallback((notification: Omit<Notification, 'id' | 'createdAt'>) => {
    const newNotification: Notification = {
      ...notification,
      id: `notif-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      createdAt: new Date().toISOString()
    }

    setNotifications((current) => [newNotification, ...(current || [])])

    const priorityMap = {
      low: 'low' as const,
      medium: 'medium' as const,
      high: 'high' as const,
      critical: 'critical' as const
    }
    const pushPriority = priorityMap[notification.priority || 'medium']

    sendNotification(notification.title, {
      body: notification.message,
      priority: pushPriority,
      tag: notification.type,
      onClick: notification.link ? () => {
        if (notification.link) {
          const viewMap: Record<string, string> = {
            '/trainer-availability': 'trainer-availability',
            '/burnout-dashboard': 'burnout-dashboard',
            '/certifications': 'certifications',
            '/trainer-wellness': 'trainer-wellness',
            '/notifications': 'notifications'
          }
          const view = viewMap[notification.link]
          if (view) {
            setActiveView(view)
          }
        }
      } : undefined
    })

    if (notification.priority === 'critical' || notification.priority === 'high') {
      const icon = notification.priority === 'critical' ? '🚨' : '⚠️'
      toast.error(`${icon} ${notification.title}`, {
        description: notification.message,
        duration: 8000
      })
    }
  }, [setNotifications, sendNotification])

  useUtilizationNotifications(safeUsers, safeSessions, handleCreateNotification)

  useCertificationNotifications(safeUsers, handleCreateNotification, setUsers)

  const currentUser: User = safeUsers[0] || {
    id: '1',
    name: 'Admin User',
    email: 'admin@company.com',
    role: 'admin',
    department: 'Administration',
    certifications: [],
    hireDate: new Date().toISOString()
  }

  const upcomingSessions = safeSessions
    .filter(s => new Date(s.startTime) > new Date())
    .sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime())
    .slice(0, 10)

  const unreadNotifications = safeNotifications.filter(n => !n.read)

  /**
   * Handles navigation events raised by child views by updating the active
   * view state.
   *
   * @param view - The key of the view to navigate to (e.g. `'dashboard'`,
   *   `'schedule'`, `'people'`).
   * @param data - Optional contextual data passed by the originating view
   *   (currently unused but forwarded for future extensibility).
   */
  const handleNavigate = (view: string, data?: any) => {
    setActiveView(view)
  }

  /**
   * Creates a single new {@link Session} with a generated ID, applying
   * sensible defaults for any omitted fields, and appends it to the sessions
   * KV store.
   *
   * @param session - Partial session data supplied by the caller. Missing
   *   required fields fall back to safe defaults (e.g. empty strings, the
   *   current timestamp, a capacity of 20).
   */
  const handleCreateSession = (session: Partial<Session>) => {
    const newSession: Session = {
      id: `session-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      courseId: session.courseId || '',
      trainerId: session.trainerId || '',
      title: session.title || 'Untitled Session',
      startTime: session.startTime || new Date().toISOString(),
      endTime: session.endTime || new Date().toISOString(),
      location: session.location || 'TBD',
      capacity: session.capacity || 20,
      enrolledStudents: session.enrolledStudents || [],
      status: session.status || 'scheduled',
      ...(session.recurrence && { recurrence: session.recurrence })
    }

    setSessions((currentSessions) => [...(currentSessions || []), newSession])
  }

  /**
   * Creates multiple {@link Session} records in a single KV update. Each
   * entry receives a unique generated ID and the same default-filling logic
   * applied by {@link handleCreateSession}. Used by schedule templates to
   * expand a template into a batch of concrete sessions.
   *
   * @param sessions - An array of partial session data objects.
   */
  const handleCreateMultipleSessions = (sessions: Partial<Session>[]) => {
    const newSessions: Session[] = sessions.map(session => ({
      id: `session-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      courseId: session.courseId || '',
      trainerId: session.trainerId || '',
      title: session.title || 'Untitled Session',
      startTime: session.startTime || new Date().toISOString(),
      endTime: session.endTime || new Date().toISOString(),
      location: session.location || 'TBD',
      capacity: session.capacity || 20,
      enrolledStudents: session.enrolledStudents || [],
      status: session.status || 'scheduled',
      ...(session.recurrence && { recurrence: session.recurrence })
    }))

    setSessions((currentSessions) => [...(currentSessions || []), ...newSessions])
  }

  /**
   * Applies a partial update to an existing session identified by `id`. Only
   * the provided fields in `updates` are merged; all other fields remain
   * unchanged.
   *
   * @param id - The unique identifier of the session to update.
   * @param updates - The fields to merge into the existing session record.
   */
  const handleUpdateSession = (id: string, updates: Partial<Session>) => {
    setSessions((currentSessions) =>
      (currentSessions || []).map(session =>
        session.id === id ? { ...session, ...updates } : session
      )
    )
  }

  /**
   * Replaces an existing user record in the KV store with the fully updated
   * {@link User} object, matched by `id`.
   *
   * @param updatedUser - The complete updated user object. Must have the same
   *   `id` as the record it replaces.
   */
  const handleUpdateUser = (updatedUser: User) => {
    setUsers((currentUsers) =>
      (currentUsers || []).map(user =>
        user.id === updatedUser.id ? updatedUser : user
      )
    )
  }

  /**
   * Appends a new {@link User} to the users KV store.
   *
   * @param newUser - The fully constructed user record to add.
   */
  const handleAddUser = (newUser: User) => {
    setUsers((currentUsers) => [...(currentUsers || []), newUser])
  }

  /**
   * Removes a user from the users KV store and cleans up related session
   * records: sessions where the deleted user was the trainer have their
   * `trainerId` cleared, and sessions where the user was an enrolled student
   * have the user's ID removed from `enrolledStudents`.
   *
   * @param userId - The unique identifier of the user to delete.
   */
  const handleDeleteUser = (userId: string) => {
    setUsers((currentUsers) => (currentUsers || []).filter(user => user.id !== userId))
    setSessions((currentSessions) => (currentSessions || []).map(session => {
      if (session.trainerId === userId) {
        return { ...session, trainerId: '', status: 'scheduled' as const }
      }
      if (session.enrolledStudents.includes(userId)) {
        return { ...session, enrolledStudents: session.enrolledStudents.filter(id => id !== userId) }
      }
      return session
    }))
  }

  /**
   * Adds a new {@link CertificationRecord} to the `trainerProfile` of each
   * trainer listed in `trainerIds`. Non-trainer users and users not present in
   * `trainerIds` are left unchanged. The new record is initialised with
   * `status: 'active'`, `renewalRequired: false`, and `remindersSent: 0`.
   *
   * @param trainerIds - IDs of the trainer users to receive the certification.
   * @param certification - Certification data excluding the computed fields
   *   (`status`, `renewalRequired`, `remindersSent`).
   */
  const handleAddCertification = useCallback((trainerIds: string[], certification: Omit<CertificationRecord, 'status' | 'renewalRequired' | 'remindersSent'>) => {
    setUsers((currentUsers) =>
      (currentUsers || []).map(user => {
        if (!trainerIds.includes(user.id) || user.role !== 'trainer') {
          return user
        }

        const newCertificationRecord: CertificationRecord = {
          ...certification,
          status: 'active',
          renewalRequired: false,
          remindersSent: 0
        }

        const existingRecords = user.trainerProfile?.certificationRecords || []

        return {
          ...user,
          trainerProfile: {
            ...user.trainerProfile!,
            certificationRecords: [...existingRecords, newCertificationRecord]
          }
        }
      })
    )
  }, [setUsers])

  /**
   * Marks a single notification as read by setting its `read` flag to `true`.
   *
   * @param id - The unique identifier of the notification to mark as read.
   */
  const handleMarkNotificationAsRead = useCallback((id: string) => {
    setNotifications((current) =>
      (current || []).map(notif =>
        notif.id === id ? { ...notif, read: true } : notif
      )
    )
  }, [setNotifications])

  /**
   * Marks a single notification as unread by setting its `read` flag to
   * `false`.
   *
   * @param id - The unique identifier of the notification to mark as unread.
   */
  const handleMarkNotificationAsUnread = useCallback((id: string) => {
    setNotifications((current) =>
      (current || []).map(notif =>
        notif.id === id ? { ...notif, read: false } : notif
      )
    )
  }, [setNotifications])

  /**
   * Marks every notification in the store as read by setting `read: true` on
   * all records.
   */
  const handleMarkAllNotificationsAsRead = useCallback(() => {
    setNotifications((current) =>
      (current || []).map(notif => ({ ...notif, read: true }))
    )
  }, [setNotifications])

  /**
   * Permanently removes a single notification from the store.
   *
   * @param id - The unique identifier of the notification to dismiss.
   */
  const handleDismissNotification = useCallback((id: string) => {
    setNotifications((current) =>
      (current || []).filter(notif => notif.id !== id)
    )
  }, [setNotifications])

  /**
   * Bulk-removes notifications from the store. When `filter` is `'read'`, only
   * already-read notifications are removed; otherwise all notifications are
   * cleared.
   *
   * @param filter - Optional scope of the dismissal. Pass `'read'` to remove
   *   only read notifications, or omit / pass `'all'` to clear everything.
   */
  const handleDismissAllNotifications = useCallback((filter?: 'all' | 'read') => {
    setNotifications((current) => {
      if (filter === 'read') {
        return (current || []).filter(notif => !notif.read)
      }
      return []
    })
  }, [setNotifications])

  /**
   * Returns the JSX for the currently active view, selected by the
   * `activeView` state string. Each case passes the relevant slice of
   * application state and the appropriate handler callbacks down to the
   * corresponding view component. Falls back to rendering the
   * {@link Dashboard} for any unknown view key.
   *
   * @returns The React element for the active view.
   */
  const renderView = () => {
    switch (activeView) {
      case 'dashboard':
        return (
          <Dashboard
            currentUser={currentUser}
            upcomingSessions={upcomingSessions}
            notifications={safeNotifications}
            enrollments={safeEnrollments}
            courses={safeCourses}
            onNavigate={handleNavigate}
            onMarkNotificationAsRead={handleMarkNotificationAsRead}
            onDismissNotification={handleDismissNotification}
          />
        )
      case 'schedule':
        return (
          <Schedule
            sessions={safeSessions}
            courses={safeCourses}
            users={safeUsers}
            currentUser={currentUser}
            onCreateSession={handleCreateSession}
            onUpdateSession={handleUpdateSession}
            onNavigate={handleNavigate}
          />
        )
      case 'schedule-templates':
        return (
          <ScheduleTemplates
            courses={safeCourses}
            onNavigate={handleNavigate}
            onCreateSessions={handleCreateMultipleSessions}
          />
        )
      case 'courses':
        return (
          <Courses
            courses={safeCourses}
            enrollments={safeEnrollments}
            currentUser={currentUser}
            onNavigate={handleNavigate}
          />
        )
      case 'people':
        return (
          <People
            users={safeUsers}
            enrollments={safeEnrollments}
            courses={safeCourses}
            sessions={safeSessions}
            currentUser={currentUser}
            onNavigate={handleNavigate}
            onUpdateUser={handleUpdateUser}
            onAddUser={handleAddUser}
            onDeleteUser={handleDeleteUser}
          />
        )
      case 'analytics':
        return (
          <Analytics
            users={safeUsers}
            enrollments={safeEnrollments}
            sessions={safeSessions}
            courses={safeCourses}
          />
        )
      case 'trainer-availability':
        return (
          <TrainerAvailability
            users={safeUsers}
            sessions={safeSessions}
            courses={safeCourses}
            onNavigate={handleNavigate}
          />
        )
      case 'burnout-dashboard':
        return (
          <BurnoutDashboard
            users={safeUsers}
            sessions={safeSessions}
            courses={safeCourses}
            onNavigate={handleNavigate}
          />
        )
      case 'certifications':
        return (
          <CertificationDashboard
            users={safeUsers}
            onNavigate={handleNavigate}
            onAddCertification={handleAddCertification}
          />
        )
      case 'trainer-wellness':
        return (
          <TrainerWellness
            users={safeUsers}
            sessions={safeSessions}
            currentUser={currentUser}
            onNavigate={handleNavigate}
          />
        )
      case 'notifications':
        return (
          <Notifications
            notifications={safeNotifications}
            onMarkAsRead={handleMarkNotificationAsRead}
            onMarkAsUnread={handleMarkNotificationAsUnread}
            onMarkAllAsRead={handleMarkAllNotificationsAsRead}
            onDismiss={handleDismissNotification}
            onDismissAll={handleDismissAllNotifications}
            onNavigate={handleNavigate}
          />
        )
      case 'user-guide':
        return <UserGuide />
      case 'settings':
        return (
          <div className="p-6">
            <div className="mb-6">
              <h1 className="text-3xl font-semibold">Settings</h1>
              <p className="text-muted-foreground mt-1">Configure system settings</p>
            </div>
            <div className="max-w-4xl space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Preview Test Data</CardTitle>
                  <CardDescription>
                    Load a deterministic fake dataset for testing all major workflows and edge cases.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="text-sm text-muted-foreground">
                    Current preview mode: <span className="font-medium text-foreground">{previewSeedMode}</span>
                  </div>
                  <div className="flex flex-wrap gap-3">
                    <Button onClick={handleLoadPreviewSeedData}>Load Seed Data</Button>
                    <Button variant="destructive" onClick={handleResetPreviewData}>Reset Preview Data</Button>
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Load will overwrite existing local data after confirmation. Reset clears all local preview records.
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        )
      default:
        return (
          <Dashboard
            currentUser={currentUser}
            upcomingSessions={upcomingSessions}
            notifications={safeNotifications}
            enrollments={safeEnrollments}
            courses={safeCourses}
            onNavigate={handleNavigate}
          />
        )
    }
  }

  return (
    <>
      <Layout
        activeView={activeView}
        onNavigate={handleNavigate}
        notificationCount={unreadNotifications.length}
        userRole={currentUser.role}
      >
        {renderView()}
      </Layout>
      <NotificationPermissionBanner />
      <Toaster />
    </>
  )
}

export default App
